apiVersion: v1
data:
  dynamic-configs.toml: |
    [http]
      [http.routers]
          [http.routers.echo_service_headless]
          entryPoints = ['web']
          rule = "PathPrefix(`/echo.`)"
          service = "echo_service"
    [http.services]
        [http.services.echo_service]
            [http.services.echo_service.loadBalancer]
                [[http.services.echo_service.loadBalancer.servers]]
                url =  "h2c://echo:50051"
kind: ConfigMap
metadata:
  name: dynamic-config
