apiVersion: v1
kind: Service
metadata:
  name: traefik
spec:
  ports:
  - name: web
    port: 80
    protocol: TCP
    targetPort: 80
  - name: api
    port: 8000
    protocol: TCP
    targetPort: 8000
  - name: metrics
    port: 8080
    protocol: TCP
    targetPort: 8080
  selector:
    app: traefik
  type: ClusterIP
