apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: loadtest
  name: loadtest
spec:
  replicas: 1
  selector:
    matchLabels:
      app: loadtest
  template:
    metadata:
      labels:
        app: loadtest
    spec:
      containers:
      - image: imans77/ghz_echo_caller
        name: loadtest
