FROM phusion/baseimage

RUN apt update
RUN apt install -y wget tar
RUN wget https://github.com/bojand/ghz/releases/download/v0.46.0/ghz_0.46.0_Linux_x86_64.tar.gz
RUN tar -xzvf ghz_0.46.0_Linux_x86_64.tar.gz
COPY echo.proto .

RUN echo "./ghz --proto=./echo.proto traefik:80 --call=echo.EchoService/Echo --skipTLS --insecure --total=1000 --connections=10 --concurrency=50" > run.sh
RUN chmod +x run.sh
